name: Integration test

on:
  schedule:
    # every hour
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
    integration-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - uses: matt-ball/newman-action@v0.2.4
        with:
          collection: service-a.postman_collection.json
      
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: integration-test
          SLACK_ICON_EMOJI: ":poop:"
          SLACK_TITLE: "Integration test run"
