name: Integration test

on:
  schedule:
    # every hour
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
    integration-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - uses: anthonyvscode/newman-action@v1
        id: postman
        with:
          collection: service-a.postman_collection.json
          reporters: cli
          timeout: 10000
          timeoutRequest: 10000

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: integration-test
          SLACK_ICON_EMOJI: ":poop:"
          SLACK_TITLE: "Integration test run"
          SLACK_MESSAGE: "${{ steps.postman.outputs.summary_full }}"
