name: Release

on:
  push:
    tags:
      - "v*"

jobs:
    docker-relase:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - id: tag_name
        run: |
          echo ::set-output name=GIT_TAG::${GITHUB_REF#refs/tags/}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${GITHUB_REPOSITORY}:${steps.tag_name.outputs.GIT_TAG}"
